services:
  api1: &api
    build: .
    command: bash -c "uvicorn src.api.app:app --host 0.0.0.0 --port 8080"
    hostname: api01
    ports:
      - "8081:8080"
    volumes:
      - ./src:/src
    environment:
      - DATABASE_URL=postgresql://postgresql:postgresql@123456@db:5432/rinha_backend
      - DB_USERNAME=postgresql
      - DB_SECRET=postgresql@123456
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rinha_backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: juntosomosmais
