name: Juntos Somos Mais API

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Taskipy
      run: |
        python -m pip install --upgrade pip
        pip install taskipy

    - name: Build Docker Image
      run: task build-no-cache

    - name: Run Unit Tests
      run: task test
