name: Juntos Somos Mais API

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Requirements
      run: pip3 install -r requirements.txt

    - name: Build Docker image
      run: task build-no-cache

    - name: Run tests
      run: task test
