name: Juntos Somos Mais API

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Taskipy
      run: |
        python -m pip install --upgrade pip
        pip install taskipy

    - name: Build Docker Image
      run: task build-no-cache

    - name: Run Unit Tests
      run: task test-pipeline

    - name: Install Heroku
      run: task heroku

    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        justlogin: true
    - run: heroku auth:whoami

    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 

    - name: Build and push Docker image
      run: |
        heroku container:push juntos-somos-mais-api -a juntos-somos-mais-api
        heroku container:release juntos-somos-mais-api -a juntos-somos-mais-api
